// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./components/Banner.vue')['default']
    EhoSvg: typeof import('./components/EhoSvg.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LogoSvg: typeof import('./components/LogoSvg.vue')['default']
  }
}
